#!/usr/bin/env python3
"""Generation driver for the confirmation census (MPS share).

Governed by notes/confirmation-census-prereg.md. Read it before running.

Design fixed by the prereg: temp 1.0, 8 draws per prompt, the 71 full-coverage
battery prompts, max 200 new tokens, single backend per arm, backend recorded.

CACHE SAFETY. The generations stash is keyed {model, prompt, temp, idx} with no
backend field, so writing here could silently mix confirmation draws into the
existing census generations for the same model. Two guards:
  1. A collision check refuses to write any key that already exists. The default
     is to ABORT the arm, not to skip, because a partial collision means the arm
     was already generated by some other run and the provenance is ambiguous.
  2. Every write is logged to a sidecar manifest (model, prompt, temp, idx,
     backend, run_id, timestamp) so provenance is recoverable per draw.

HOLD. This script does not run unless --go is passed. The prereg allows free
amendment of thresholds until generation begins; --go is the line.

Usage:
    uv run python scripts/confirmation_generate.py --arms tinyllama,stablelm --dry-run
    uv run python scripts/confirmation_generate.py --arms tinyllama --go
"""
import argparse, csv, datetime, gc, json, os, sys, time

import torch

from malign_logits.cache import get_cache
from malign_logits.models import load_model
from malign_logits import MODEL_FAMILIES
import malign_logits.experiments as E

MANIFEST = "data/confirmation_generation_manifest.csv"
TEMP, N_DRAWS, MAX_NEW = 1.0, 8, 200
MANIFEST_COLS = ["run_id", "backend", "family", "role", "model", "prompt",
                 "temp", "idx", "n_tokens", "timestamp"]


def battery_prompts(cm, path=None):
    """Load the frozen battery instead of recomputing, when a path is given.

    Recomputing requires the full generations stash (it selects prompts with
    >=12 families of existing base+aligned coverage). On the cloud share that
    would mean shipping ~80 GB of local stash to pick 71 strings. Freezing them
    to a 4 KB JSON keeps the CLOUD AND MPS SHARES ON THE IDENTICAL PROMPT SET,
    which matters more than the bandwidth: recomputing remotely against a
    different stash state could silently select a different battery.
    """
    if path:
        with open(path) as f:
            return json.load(f)
    return _battery_prompts_from_cache(cm)


def _battery_prompts_from_cache(cm):
    """The 71 full-coverage prompts: DEFAULT_PROMPTS restricted to those with
    existing base+aligned generations in at least 12 families."""
    dp = E.DEFAULT_PROMPTS
    prompts = list(dp.values()) if isinstance(dp, dict) else list(dp)
    fams = [(k, f.base, f.superego) for k, f in MODEL_FAMILIES.items()
            if f.base and getattr(f, "superego", None)]
    keep = []
    for p in prompts:
        n = sum(1 for _, b, a in fams
                if cm.count_generations(b, p) > 0 and cm.count_generations(a, p) > 0)
        if n >= 12:
            keep.append(p)
    return keep


def collisions(cm, model, prompts):
    return [(p, i) for p in prompts for i in range(N_DRAWS)
            if cm.get_generation(model, p, temp=TEMP, idx=i) is not None]


def append_manifest(rows):
    new = not os.path.exists(MANIFEST)
    with open(MANIFEST, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=MANIFEST_COLS)
        if new:
            w.writeheader()
        w.writerows(rows)


def run_arm_vllm(cm, family, role, model_id, prompts, backend, run_id, tp=1,
                 sidecar=None, log=print):
    """vLLM path for the cloud share.

    Shares the collision guard, manifest, battery selection, and cache keys with
    the MPS path -- only the generation call differs. That matters because the
    prereg records backend as a covariate: if the two backends went through
    different drivers, a backend effect and a driver effect would be
    inseparable.
    """
    from vllm import LLM, SamplingParams
    # Sidecar mode: the registered cross-backend sanity pair needs the SAME
    # model+prompt+temp+idx generated on a second backend, but the stash key has
    # no backend field, so writing them there would collide on every key. These
    # draws feed only the backend comparison and never the main analysis, so
    # they go to a JSONL file instead and the stash keeps one entry per key.
    # (desktop ruling 2026-07-26, option (a); logged as implementation note.)
    coll = [] if sidecar else collisions(cm, model_id, prompts)
    if coll:
        log(f"  ABORT {family}/{role}: {len(coll)} of {len(prompts)*N_DRAWS} keys "
            f"already exist in the generations stash (e.g. idx {coll[0][1]}).")
        return False
    llm = LLM(model=model_id, tensor_parallel_size=tp, dtype="auto",
              trust_remote_code=True)
    sampling = SamplingParams(temperature=TEMP, max_tokens=MAX_NEW, n=N_DRAWS)
    t0 = time.time()
    outs = llm.generate(prompts, sampling)
    rows, n = [], 0
    sc = open(sidecar, "a") if sidecar else None
    for p, out in zip(prompts, outs):
        for i, comp in enumerate(out.outputs[:N_DRAWS]):
            if sc:
                sc.write(json.dumps({"model": model_id, "prompt": p, "temp": TEMP,
                                     "idx": i, "backend": backend, "run_id": run_id,
                                     "family": family, "role": role,
                                     "text": comp.text}) + "\n")
            else:
                cm.set_generation(model_id, p, comp.text, temp=TEMP, idx=i)
            rows.append(dict(run_id=run_id, backend=backend, family=family, role=role,
                             model=model_id, prompt=p, temp=TEMP, idx=i,
                             n_tokens=len(comp.token_ids),
                             timestamp=datetime.datetime.now().isoformat(timespec="seconds")))
            n += 1
        if len(rows) >= 200:
            append_manifest(rows); rows = []
    if rows:
        append_manifest(rows)
    if sc:
        sc.close()
        log(f"  [sidecar] {n} draws -> {sidecar} (not written to the stash)")
    del llm
    gc.collect()
    log(f"  {family}/{role}: {n} generations in {time.time()-t0:.0f}s [vllm]")
    return True


def run_arm(cm, family, role, model_id, prompts, backend, run_id, log=print):
    coll = collisions(cm, model_id, prompts)
    if coll:
        log(f"  ABORT {family}/{role}: {len(coll)} of {len(prompts)*N_DRAWS} keys "
            f"already exist in the generations stash (e.g. idx {coll[0][1]}). "
            f"Provenance would be ambiguous; resolve before generating.")
        return False
    model, tok = load_model(model_id)
    t0, n = time.time(), 0
    rows = []
    for p in prompts:
        ids = tok.encode(p, return_tensors="pt").to(next(model.parameters()).device)
        # all N_DRAWS in one call: same independent samples at temp 1.0, ~8x faster
        # than looping generate(), and identical in distribution.
        with torch.no_grad():
            out = model.generate(ids, do_sample=True, temperature=TEMP,
                                 num_return_sequences=N_DRAWS,
                                 max_new_tokens=MAX_NEW,
                                 pad_token_id=tok.pad_token_id or tok.eos_token_id)
        for i in range(N_DRAWS):
            txt = tok.decode(out[i][ids.shape[1]:], skip_special_tokens=True)
            cm.set_generation(model_id, p, txt, temp=TEMP, idx=i)
            rows.append(dict(run_id=run_id, backend=backend, family=family, role=role,
                             model=model_id, prompt=p, temp=TEMP, idx=i,
                             n_tokens=int(out.shape[1] - ids.shape[1]),
                             timestamp=datetime.datetime.now().isoformat(timespec="seconds")))
            n += 1
        if len(rows) >= 200:
            append_manifest(rows); rows = []
    if rows:
        append_manifest(rows)
    del model
    gc.collect()
    if torch.backends.mps.is_available():
        torch.mps.empty_cache()
    log(f"  {family}/{role}: {n} generations in {time.time()-t0:.0f}s")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arms", required=True, help="comma-separated family keys")
    ap.add_argument("--backend", default="mps", choices=["mps", "vllm"],
                    help="mps = HF generate (local); vllm = batched (cloud share)")
    ap.add_argument("--tp", type=int, default=1, help="vllm tensor-parallel size")
    ap.add_argument("--prompts-file", help="frozen battery JSON (see battery_prompts)")
    ap.add_argument("--sidecar", help="write draws to this JSONL instead of the stash "
                                      "(cross-backend sanity pair; bypasses the collision guard)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--go", action="store_true",
                    help="required to generate. Without it the script reports and exits, "
                         "because the prereg allows threshold amendment until generation begins.")
    a = ap.parse_args()

    cm = get_cache()
    prompts = battery_prompts(cm, a.prompts_file)
    arms = [x.strip() for x in a.arms.split(",") if x.strip()]
    print(f"{len(prompts)} battery prompts x {N_DRAWS} draws x {len(arms)} families "
          f"x 2 roles = {len(prompts)*N_DRAWS*len(arms)*2} generations")
    print(f"temp={TEMP} max_new={MAX_NEW} backend={a.backend}\n")

    plan = []
    for k in arms:
        f = MODEL_FAMILIES.get(k)
        if f is None or not f.base or not getattr(f, "superego", None):
            print(f"  {k}: NOT A PAIRED FAMILY, skipping"); continue
        for role, m in (("base", f.base), ("aligned", f.superego)):
            c = collisions(cm, m, prompts)
            print(f"  {k:14s} {role:8s} {m.split('/')[-1]:34s} "
                  f"{'COLLISION ' + str(len(c)) if c else 'clear'}")
            plan.append((k, role, m))
    if a.dry_run or not a.go:
        print("\nHOLDING. Re-run with --go to generate. "
              "(Prereg: thresholds may be amended freely until generation begins.)")
        return

    run_id = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")
    print(f"\nrun_id={run_id}; manifest -> {MANIFEST}\n")
    # PER-ARM ISOLATION. Without it one unloadable model kills the whole run:
    # on 2026-07-26 Baichuan2 (architecture removed from vLLM) took internlm2 and
    # redpajama down with it, then internlm2 (remote-code forward signature drift)
    # took redpajama down a second time. An arm that cannot load is a datum about
    # census reach, not a reason to abandon the arms behind it.
    failed = []
    for k, role, m in plan:
        try:
            if a.backend == "vllm":
                run_arm_vllm(cm, k, role, m, prompts, a.backend, run_id, tp=a.tp,
                             sidecar=a.sidecar)
            else:
                run_arm(cm, k, role, m, prompts, a.backend, run_id)
        except Exception as e:
            failed.append((k, role, m, f"{type(e).__name__}: {e}"))
            print(f"  ARM FAILED {k}/{role} ({m}): {type(e).__name__}: {e}")
            print("  continuing with the remaining arms")
            gc.collect()
            if torch.backends.mps.is_available():
                torch.mps.empty_cache()
    if failed:
        print(f"\n{len(failed)} arm(s) failed:")
        for k, role, m, err in failed:
            print(f"  {k}/{role}  {m}\n    {err[:160]}")


if __name__ == "__main__":
    main()
