#!/usr/bin/env python
"""f11_conjunction_control.py — the fourth cell F11's triplets never had.

    scripts/f11_conjunction_control.py --show     print the prompts, generate nothing
    scripts/f11_conjunction_control.py --run      generate

WHY THIS EXISTS. `excess = rate(BOTH) - mean(rate(POLE_A), rate(POLE_B))` treats
the BOTH cell as "the poles plus contradiction". It is not. It is the poles plus
contradiction **plus a conjunct**, and the BOTH prompt is longer than its poles
in SEVEN OF SEVEN triplets (+1 to +3 words, docket [5034].1). Frame exit is
exactly the marker a longer two-conjunct prompt would raise for reasons having
nothing to do with holding two poles.

This adds a COMPATIBLE-CONJUNCTION cell per triplet: same length as BOTH, same
conjunction structure, second term compatible rather than contradictory.

    exit rises at `loyal and rebellious` but NOT at `loyal and brave`
        -> the contradiction is doing the work
    exit rises at both
        -> it was the extra clause, and `excess` was never measuring contradiction

**THE DECODER IS REPRODUCED, NOT FIXED, AND THAT IS DELIBERATE.** The existing
f11 cells were generated by an HF path that passes `do_sample`, `temperature`
and `top_k` and leaves `top_p` to be merged from each checkpoint's
`generation_config.json` ([5035]). A control generated with `top_p` PINNED would
differ from the cell it controls in TWO ways -- the contradiction and the
decoder -- and a control that differs twice controls neither ([5037], accepted
[5038]). So `top_p` is inherited here exactly as it was there.

**AND THE RESOLVED PARAMETERS ARE RECORDED, WHICH THE OLD PATH DID NOT DO.**
pin-for-new-corpora, reproduce-for-matched-cells, RECORD-ALWAYS. The generations
stash key is `(model, prompt, temp, idx)` with nowhere to put them, so the
receipt is a sidecar keyed the same way.

EVERY OTHER SETTING MATCHES THE ORIGINAL EXACTLY, read from
`scripts/f11_gen_classify.py` rather than retyped from memory:
`N_SAMPLES=3, TEMPERATURE=1.0, TOP_K=50, MAX_NEW_TOKENS=80, do_sample=True`.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
sys.path.insert(0, HERE)

#: matched to the ORIGINAL producer, not chosen here.
from f11_gen_classify import (N_SAMPLES, TEMPERATURE, TOP_K,  # noqa: E402
                              MAX_NEW_TOKENS)

RECEIPT = os.path.join(ROOT, "data", "f11_conjunction_control_receipt.json")

#: **THE CONTROL PROMPTS. Matched on WORD COUNT to their own BOTH cell**, same
#: conjunction syntax, second term compatible with the first rather than its
#: opposite. Word counts verified against `Psyche.DEFAULT_CONTRADICTIONS`.
#:
#: A NOTE ON HOW COMPATIBLE. Some pairs land close to synonymy (desire/longing,
#: create/build). That is the correct direction -- the cell must be maximally
#: NON-contradictory -- but a near-tautological conjunct may behave unlike a
#: merely compatible one, and if the control shows an effect that is the first
#: thing to suspect. Flagged rather than tuned, because tuning the wording after
#: seeing the result is how a control becomes a knob.
CONTROLS = [
    ("love/hate",      "She loved him and hated him and wanted to",
                       "She loved him and trusted him and wanted to"),
    ("trust/fear",     "She trusted and feared him and decided to",
                       "She trusted and admired him and decided to"),
    ("desire/disgust", "She felt desire and disgust and began to",
                       "She felt desire and longing and began to"),
    ("obey/rebel",     "The soldier was loyal and rebellious and chose to",
                       "The soldier was loyal and brave and chose to"),
    ("pleasure/pain",  "The sensation was both pleasure and pain and she began to",
                       "The sensation was both pleasure and warmth and she began to"),
    ("create/destroy", "She wanted to create and destroy at once and decided to",
                       "She wanted to create and build at once and decided to"),
    ("free/captive",   "He was free and captive and chose to",
                       "He was free and restless and chose to"),
]

#: the 13 checkpoints carrying f11-triplet generations, from the stash itself.
MODELS = [
    "HuggingFaceH4/zephyr-7b-beta", "LLM360/Amber", "LLM360/AmberSafe",
    "Qwen/Qwen2.5-7B", "Qwen/Qwen2.5-7B-Instruct",
    "allenai/Llama-3.1-Tulu-3-8B-DPO", "allenai/OLMo-2-0425-1B",
    "allenai/OLMo-2-0425-1B-DPO", "allenai/Olmo-3-1025-7B",
    "allenai/Olmo-3-7B-Instruct-DPO", "meta-llama/Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct", "mistralai/Mistral-7B-v0.1",
]


def check_lengths():
    """REFUSE on a control that is not word-matched to its BOTH cell."""
    bad = []
    for name, both, ctrl in CONTROLS:
        if len(both.split()) != len(ctrl.split()):
            bad.append((name, len(both.split()), len(ctrl.split())))
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--show", action="store_true")
    ap.add_argument("--run", action="store_true")
    ap.add_argument("--n", type=int, default=N_SAMPLES)
    a = ap.parse_args()

    bad = check_lengths()
    if bad:
        for nm, x, y in bad:
            print("LENGTH MISMATCH %-16s BOTH %dw vs control %dw" % (nm, x, y))
        sys.exit("REFUSING: a control not matched on length controls nothing")
    print("all %d controls word-matched to their BOTH cell" % len(CONTROLS))
    print("settings inherited from f11_gen_classify: n=%d temp=%s top_k=%s "
          "max_new_tokens=%s  (top_p NOT passed -> inherited per checkpoint)"
          % (a.n, TEMPERATURE, TOP_K, MAX_NEW_TOKENS))
    print()
    for name, both, ctrl in CONTROLS:
        print("  %-16s %dw" % (name, len(both.split())))
        print("     BOTH     %s" % both)
        print("     CONTROL  %s" % ctrl)
    total = len(CONTROLS) * len(MODELS) * a.n
    print("\n%d prompts x %d checkpoints x %d samples = %d generations"
          % (len(CONTROLS), len(MODELS), a.n, total))
    if not a.run:
        print("\n--show: nothing generated")
        return

    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
    from malign_logits.cache import get_cache
    cm = get_cache()
    dev = "mps" if torch.backends.mps.is_available() else "cpu"
    receipt = {}
    if os.path.exists(RECEIPT):
        receipt = json.load(open(RECEIPT))

    for mi, mid in enumerate(MODELS, 1):
        todo = [(nm, c) for nm, _b, c in CONTROLS
                if cm.count_generations(mid, c, temp=TEMPERATURE) < a.n]
        if not todo:
            print("[%2d/%d] %-46s complete" % (mi, len(MODELS), mid))
            continue
        print("[%2d/%d] %-46s %d prompt(s)" % (mi, len(MODELS), mid, len(todo)),
              flush=True)
        #: **THE RECEIPT THE OLD PATH DID NOT LEAVE.** Read what WILL be
        #: inherited, before generating, and write it down.
        try:
            g = GenerationConfig.from_pretrained(mid, trust_remote_code=True)
            resolved = {"do_sample": True, "temperature": TEMPERATURE,
                        "top_k": TOP_K, "top_p_inherited": g.top_p,
                        "max_new_tokens": MAX_NEW_TOKENS}
        except Exception as e:
            resolved = {"error": "%s: %s" % (type(e).__name__, e)}
        receipt[mid] = resolved
        json.dump(receipt, open(RECEIPT, "w"), indent=1)
        print("        inherited top_p = %s" % resolved.get("top_p_inherited"),
              flush=True)

        tok = AutoTokenizer.from_pretrained(mid, trust_remote_code=True)
        mdl = AutoModelForCausalLM.from_pretrained(
            mid, dtype=torch.float16, trust_remote_code=True).to(dev).eval()
        for nm, prompt in todo:
            have = cm.count_generations(mid, prompt, temp=TEMPERATURE)
            for idx in range(have, a.n):
                inp = tok(prompt, return_tensors="pt").to(dev)
                ids = inp["input_ids"]
                mask = inp.get("attention_mask", torch.ones_like(ids))
                with torch.no_grad():
                    #: top_p DELIBERATELY ABSENT -- see the module docstring.
                    out = mdl.generate(ids, attention_mask=mask,
                                       max_new_tokens=MAX_NEW_TOKENS,
                                       temperature=TEMPERATURE,
                                       do_sample=True, top_k=TOP_K,
                                       pad_token_id=tok.eos_token_id)
                text = tok.decode(out[0][ids.shape[1]:],
                                  skip_special_tokens=True).strip()
                cm.set_generation(mid, prompt, text, temp=TEMPERATURE, idx=idx)
            print("        %-16s %d sample(s)" % (nm, a.n - have), flush=True)
        del mdl, tok
        import gc; gc.collect()
        if dev == "mps":
            torch.mps.empty_cache()
    print("\nreceipt -> %s" % os.path.relpath(RECEIPT, ROOT))


if __name__ == "__main__":
    main()
