#!/usr/bin/env python
"""fc_checkAC.py — lacan's [4961] checks A and C on all 27 wave-3 pairs.

    scripts/fc_checkAC.py

Commissioned at [4965] under RH's authority after [4964] was reopened. [4964]
named both of these as UNRUN and named check A as the sharp one, because bloomz
is an mT0-style multilingual finetune of bloom and a shared-vocabulary
assumption across arms is worth testing rather than assuming.

## THIS FILE IS THE TIMESTAMP

It is committed BEFORE it is run. Every threshold below is fixed here, and none
of them is keyed on `dd`, `own`, `swap`, or any quantity under test. That
ordering is the entire point: [4961] existed because an exclusion was made after
seeing the values it changed, and a rule invented after an exclusion cannot
exonerate the exclusion.

**The outcome I expect to be resisted is bloom passing again.** Naming it here,
before running, for the second time.

## CHECK A — VOCABULARY COMMENSURABILITY.  Declared at [4961].

    "For a sample of shared words, do both arms encode to the same token COUNT?
     THRESHOLD: >5% of sampled shared words differing in token count across arms."

Precedent: the H4 checkpoints double-encode the leading space, so
`zephyr-7b-beta` scored ~60% of shared words multi-token where
`mistral-7b-v0.1` scored them single-token.

Computed from stored bytes, no tokenizer downloads. Every forced record carries
`n_forced_tokens` (the appended word's token count under the GENERATING model)
and `prompt_len` (prompt + forced tokens). The same (prompt, word, arm) cell
exists under role=base and role=aligned, generated by the two different models.
So the arms' tokenizations of one string sit side by side in the store.

**This is the form malign withdrew, corrected.** Their check required one prompt
string to yield one `prompt_len` WITHIN a pair, which fires on 26/27 because the
forced arms append a word and the key carries the base prompt. Comparing the two
ROLES at a fixed (prompt, word, arm) holds the appended word constant, so what
is left is the tokenizer.

Two statistics, both reported, the first decisive:

    A1  % of shared (prompt, word) cells where n_forced_tokens differs by role
    A2  % of shared (prompt, word, arm) cells where prompt_len differs by role

A1 is the declared check: it is literally "does this word encode to the same
token count under both arms". A2 is the same question about the prompt and is
reported because a tokenizer that agrees on the appended word can still disagree
on the sentence. **A pair fails check A on A1 > 5%.** A2 is reported, not
adjudicated, because [4961] declared the threshold for words.

## CHECK C — MASS CONSERVATION.  Declared at [4961].

    "Stored probability mass per arm over the scored support.
     THRESHOLD: arm mass outside [0.80, 1.05], or the two arms differing by >0.10."

Precedent: unnormalised `word_probs` summing to 0.899 base / 0.933 aligned
claimed ~7% of mass outside the system and depressed survival uniformly.

**THE DECLARED BAND DOES NOT TRANSFER AND I AM SAYING SO BEFORE RUNNING, NOT
AFTER.** [0.80, 1.05] was written for `word_probs`, a distribution over a word
list that genuinely should sum to ~1. The beam-corpus analogue is sequence mass
over 100 beams of 10 tokens, which has no reason to sit near 1 for any model,
clean or not. Applying that band here would fail everyone and diagnose nothing.

So C is run in two forms and only one of them adjudicates:

**C1 — THE CONSERVATION IDENTITY, and it needs no threshold from the data.**
Beam search stores its own `log_prob` per beam. `scored_by_<generating role>`
re-scores the identical token sequence under the identical model. In exact
arithmetic these are the same number. A disagreement means the generation path
and the scoring path were not the same model state — which is exactly a defect
that produces a wild `dd` with clean text, and the reason [4964] could exonerate
bloom on text and still not account for its -0.41.

    tolerance   |log_prob - sum(own_scores)| > 0.5 nats on one beam
    pair fails  > 5% of ELIGIBLE beams over tolerance

0.5 nats is a factor of 1.6 in probability. Float32 accumulation over ten terms
of order 1-10 gives ~1e-4, so the tolerance is generous by three orders of
magnitude and is not near any clean value. The 5% rate mirrors check A's, the
only rate precedent this battery has.

**ELIGIBLE excludes EOS-padded beams.** A beam that terminated early is padded
to ten slots; `log_prob` covers the real tokens and the re-score covers all ten,
so the identity is expected to fail there and its failure means nothing. A
trailing run of >=2 identical token ids at the end of the sequence is treated as
padding and the beam is dropped. This is conservative in the direction of
CLEARING pairs, which is the direction that goes against convicting bloom.

**C2 — SEQUENCE MASS, reported and not adjudicated.** sum_b exp(sum_t s[b][t])
per arm over eligible beams: the fraction of sequence space the 100 beams cover
under each model. The declared band is printed beside it so the reader can see
it does not apply. The ARM RATIO is the informative part — a pair whose two arms
cover wildly different amounts of their own sequence space is not comparable
across arms whatever the absolute numbers are — but **no threshold on it was
declared in advance, so it is described and nothing is excluded on it.**

## POPULATION

All 27 pairs of the [4964] canonical composition, imported from
`fc_wave3_damage.compose` rather than recomposed, so this runs on the same
population the damage tables ran on by construction. Checks apply to every pair.
Whichever pairs fail, fail.
"""
import collections
import math
import os
import statistics
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)

A_RATE = 0.05          # >5% of shared words differing in token count
C1_TOL = 0.5           # nats, per beam
C1_RATE = 0.05         # >5% of eligible beams over tolerance
C2_BAND = (0.80, 1.05)  # declared for word_probs; printed, not applied
MIN_ELIGIBLE = 20      # a pair with fewer eligible beams is UNTESTED, not clean


def pad_len(toks):
    """Length of the trailing run of one repeated token id, 0 if none."""
    if len(toks) < 2:
        return 0
    n = 1
    while n < len(toks) and toks[-1 - n] == toks[-1]:
        n += 1
    return n if n >= 2 else 0


def check_A(cells):
    """cells: {(role, arm, word, prompt): value}. Returns (a1, a2, counts)."""
    #: index the two roles at a fixed (arm, word, prompt) so the appended word
    #: is held constant and only the tokenizer varies.
    byrole = collections.defaultdict(dict)
    for (role, arm, word, prompt), v in cells.items():
        byrole[(arm, word, prompt)][role] = v

    nf_shared = nf_diff = 0
    pl_shared = pl_diff = 0
    words_diff = set()
    for (arm, word, prompt), rr in byrole.items():
        if "base" not in rr or "aligned" not in rr:
            continue
        b, a = rr["base"], rr["aligned"]
        #: n_forced_tokens is only meaningful on a forced arm; undisturbed is 0
        #: under both by construction and would dilute the rate toward clean.
        if word and arm != "undisturbed":
            nb, na = b.get("n_forced_tokens"), a.get("n_forced_tokens")
            if nb is not None and na is not None:
                nf_shared += 1
                if nb != na:
                    nf_diff += 1
                    words_diff.add(word)
        pb, pa = b.get("prompt_len"), a.get("prompt_len")
        if pb is not None and pa is not None:
            pl_shared += 1
            if pb != pa:
                pl_diff += 1
    a1 = (nf_diff / nf_shared) if nf_shared else None
    a2 = (pl_diff / pl_shared) if pl_shared else None
    return a1, a2, (nf_shared, nf_diff, pl_shared, pl_diff, sorted(words_diff)[:6])


def check_C(cells):
    """Returns (c1_rate, n_eligible, mass_base, mass_algn)."""
    over = elig = 0
    mass = {"base": [], "aligned": []}
    for (role, arm, word, prompt), v in cells.items():
        beams = v.get("beams") or []
        sb = v.get("scored_by_base") or []
        sa = v.get("scored_by_aligned") or []
        own = sb if role == "base" else sa
        keep = []
        for i, bm in enumerate(beams):
            if i >= len(own):
                break
            toks = bm.get("tokens") or []
            s = own[i]
            if len(s) != len(toks) or not toks:
                continue
            if pad_len(toks):
                continue
            keep.append(i)
            lp = bm.get("log_prob")
            if lp is None:
                continue
            elig += 1
            if abs(lp - sum(s)) > C1_TOL:
                over += 1
        #: C2 over the SAME eligible beams, so the two halves of C describe one
        #: population. exp of a sum of ten log-probs underflows for long tails;
        #: math.exp handles it as 0.0, which is the right contribution.
        for name, arr in (("base", sb), ("aligned", sa)):
            if not arr:
                continue
            tot = 0.0
            for i in keep:
                if i < len(arr):
                    try:
                        tot += math.exp(sum(arr[i]))
                    except OverflowError:
                        tot = float("inf")
            mass[name].append(tot)
    c1 = (over / elig) if elig else None
    mb = statistics.median(mass["base"]) if mass["base"] else None
    ma = statistics.median(mass["aligned"]) if mass["aligned"] else None
    return c1, elig, mb, ma


def main():
    from malign_logits.cache import get_cache
    from fc_wave3_damage import compose
    cm = get_cache()
    by = compose(cm)

    rows = []
    for pid, cells in by.items():
        if not any(k[1] == "force_faller" for k in cells):
            continue
        a1, a2, ac = check_A(cells)
        c1, nel, mb, ma = check_C(cells)
        rows.append((pid, a1, a2, ac, c1, nel, mb, ma))
    rows.sort(key=lambda r: r[0])

    print("\n" + "=" * 100)
    print("CHECK A — vocabulary commensurability.  FAIL: A1 > %.0f%%" % (A_RATE * 100))
    print("%-52s %8s %8s   %s" % ("pair", "A1", "A2", "n words / n prompts"))
    print("-" * 100)
    failA = []
    for pid, a1, a2, ac, c1, nel, mb, ma in rows:
        nfs, nfd, pls, pld, ex = ac
        f = a1 is not None and a1 > A_RATE
        if f:
            failA.append(pid)
        print("%-52s %7s %8s   %d/%d  %d/%d %s%s"
              % (pid[:52],
                 "n/a" if a1 is None else "%.2f%%" % (a1 * 100),
                 "n/a" if a2 is None else "%.2f%%" % (a2 * 100),
                 nfd, nfs, pld, pls,
                 ("  <- FAIL" if f else ""),
                 ("  eg " + ",".join(ex) if ex else "")))

    print("\n" + "=" * 100)
    print("CHECK C1 — conservation identity.  FAIL: >%.0f%% of eligible beams "
          "off by >%.1f nats" % (C1_RATE * 100, C1_TOL))
    print("%-52s %10s %10s  %10s %10s" % ("pair", "C1", "n_elig", "mass_base", "mass_algn"))
    print("-" * 100)
    failC = []
    untested = []
    for pid, a1, a2, ac, c1, nel, mb, ma in rows:
        if nel < MIN_ELIGIBLE:
            untested.append(pid)
        f = c1 is not None and c1 > C1_RATE and nel >= MIN_ELIGIBLE
        if f:
            failC.append(pid)
        print("%-52s %9s %10d  %10s %10s%s"
              % (pid[:52],
                 "n/a" if c1 is None else "%.2f%%" % (c1 * 100), nel,
                 "n/a" if mb is None else "%.3g" % mb,
                 "n/a" if ma is None else "%.3g" % ma,
                 "  <- FAIL" if f else ("  <- UNTESTED (n<%d)" % MIN_ELIGIBLE
                                        if nel < MIN_ELIGIBLE else "")))

    print("\nC2 — sequence mass. Declared band [%.2f, %.2f] was written for "
          "word_probs and is NOT applied here; printed above for the reader."
          % C2_BAND)
    print("\n" + "=" * 100)
    print("VERDICT, %d pairs" % len(rows))
    print("  check A fails : %s" % (", ".join(failA) if failA else "NONE"))
    print("  check C1 fails: %s" % (", ".join(failC) if failC else "NONE"))
    if untested:
        print("  C1 UNTESTED   : %s" % ", ".join(untested))
    bl = [r for r in rows if "bloom" in r[0]]
    if bl:
        pid, a1, a2, ac, c1, nel, mb, ma = bl[0]
        print("\n  BLOOM, the pair this was commissioned to adjudicate:")
        print("    A1 %s   A2 %s   C1 %s over %d eligible beams   mass %s / %s"
              % ("n/a" if a1 is None else "%.2f%%" % (a1 * 100),
                 "n/a" if a2 is None else "%.2f%%" % (a2 * 100),
                 "n/a" if c1 is None else "%.2f%%" % (c1 * 100), nel,
                 "n/a" if mb is None else "%.3g" % mb,
                 "n/a" if ma is None else "%.3g" % ma))
        print("    convicted by A : %s" % (pid in failA))
        print("    convicted by C1: %s" % (pid in failC))


if __name__ == "__main__":
    main()
