"""Digest receipt for the exogenous norm sets, so their pins are checkable from
any seat.

    uv run python scripts/norms_digest.py            print
    uv run python scripts/norms_digest.py --write     write meta/norms_digests.md

WHY THIS EXISTS. Registrations pin exogenous norm files by content -- e.g.
`norms Warriner 85f6d7e3, V.Mean.Sum, human/exogenous` in three M01
registrations. The files live in RH's Dropbox at
`Articles/TheoryMachines/norms_sources/` and are NOT in the repository, so a
second seat cannot recompute the digest and the pin is single-seat-verified.
Docket [5610] booked that as open. A receipt in the repo closes it: another seat
still cannot digest the file, but it can compare a registration's pin against a
committed value and see when one changes.

WHAT A RECEIPT IS AND IS NOT. It is NOT independent verification -- it is written
from the same machine that holds the files, so a wrong digest here would be
wrong in both places. What it gives a second seat is a FIXED REFERENCE: the pin
in a registration and the value in this receipt were computed at different times
by different scripts, so drift between them is visible, and any future
recomputation on any machine has something to disagree with. Independent
verification needs the file, and that is a custody question rather than a
tooling one.

THE VALUES ARE GENERATED, NEVER TYPED. On 2026-08-12 a commit hash was
hand-written into docket [5604] and did not resolve; the numbers in that same
post were machine-generated and were fine. Every digest below is computed at
write time by this script. Do not edit the table by hand -- rerun it.

TRUNCATION IS SHOWN, NOT ASSUMED. Registrations cite 8 and 16 character prefixes
of these digests, so both prefixes are printed beside the full value. A pin of a
DIFFERENT length is not a mismatch, and a reader comparing "85f6d7e3" against a
64-character string should not have to work that out.
"""
import hashlib
import os
import sys

NORMS = "/Users/rj416/Dropbox/Prof/Articles/TheoryMachines/norms_sources"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "meta", "norms_digests.md")
SKIP = {".DS_Store"}


def digest(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for b in iter(lambda: fh.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def walk():
    out = []
    for dirpath, dirnames, filenames in os.walk(NORMS):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for f in sorted(filenames):
            if f in SKIP or f.startswith("."):
                continue
            p = os.path.join(dirpath, f)
            out.append((os.path.relpath(p, NORMS), os.path.getsize(p), digest(p)))
    return out


def main():
    if not os.path.isdir(NORMS):
        print("norms_sources not reachable at %s -- this script must run on the "
              "machine that holds it, and the committed receipt is what other "
              "seats read instead." % NORMS)
        return 1
    rows = walk()
    lines = ["# Digest receipt: exogenous norm sets", "",
             "**Generated by `scripts/norms_digest.py --write`. Do not edit by hand;",
             "every value here is computed at write time.** Registrations pin these",
             "files by content and the files are not in the repository, so this is the",
             "only thing a second seat can compare a pin against.",
             "",
             "It is a REFERENCE, not independent verification: it is written from the",
             "same machine that holds the files. What it buys is drift detection --",
             "a registration's pin and this table were computed at different times by",
             "different code, so disagreement is visible.",
             "",
             "Source: `Articles/TheoryMachines/norms_sources/` (RH's Dropbox).",
             "",
             "    sha8      sha16             bytes         file"]
    for rel, size, d in rows:
        lines.append("    %-9s %-17s %12d  %s" % (d[:8], d[:16], size, rel))
    lines += ["", "## Pins currently cited in registrations", "",
              "`85f6d7e3` -- Warriner valence, cited as "
              "`norms Warriner 85f6d7e3, V.Mean.Sum, human/exogenous` in",
              "`registration_d_pairs_v1.md`, `_v5.md` and `registration_e_gap_v3.md`.",
              "Resolves in the table above; see the row whose sha8 matches.", ""]
    text = "\n".join(lines)
    if "--write" in sys.argv:
        open(OUT, "w").write(text)
        print("wrote %s (%d files)" % (os.path.relpath(OUT, ROOT), len(rows)))
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
